# Generated by Django 5.1.4 on 2025-09-25 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuienesSomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('comision', models.DecimalField(decimal_places=2, default=70.0, help_text='Porcentaje que gana el barbero (ej: 70 significa 70%)', max_digits=5)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=15)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20)),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.barbero')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DiaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('disponible', models.BooleanField(default=True)),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_laborales', to='cita.barbero')),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('barbero', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Finanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso_barbero', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingreso_admin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.barbero')),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cita.cita')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.barbero')),
                ('dia_laboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.dialaboral')),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.horariodisponible'),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicios',
            field=models.ManyToManyField(to='cita.servicio'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['confirmada', 'completada'])), fields=('cliente',), name='unique_cita_por_dia'),
        ),
    ]
