# Generated by Django 5.1.4 on 2025-09-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_alter_finanza_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbero',
            name='activo',
        ),
        migrations.AddField(
            model_name='cita',
            name='cliente_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='barbero',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
    ]
