# Generated by Django 5.1.4 on 2025-09-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_remove_barbero_activo_cita_cliente_visible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision_global', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
            ],
        ),
    ]
